[[CURRENCIES]]
code = "1ST"
issuer = "rsXo58k5Gp3EjWvxTAZ4PFxf9imDc4R2Ra"
name = "First Ledger"
desc = "TThe fastest way to trade assets on the XRP Ledger"
image = "https://violet-managing-mosquito-615.mypinata.cloud/ipfs/QmQnt4mAnw3WXp5NYUbM9xXHT8BPshRepc8vkav9Lh29Nf"
