[[CURRENCIES]]
code = "1ST"
issuer = "rsXo58k5Gp3EjWvxTAZ4PFxf9imDc4R2Ra"
name = "First Ledger"
desc = "TThe fastest way to trade assets on the XRP Ledger"
image = "https://ipfs.io/ipfs/QmWTYGBxr3NBe8rKPXPHCh71oUnf4xAe2u1UsCnTkaTfJc"
